<?php
declare(strict_types=1);
?>
<p>
    Full details of the selected event are displayed here.
    <br />
    Make any changes, choose an approval status and select any additional publishing methods,
    <br />
    then click Submit to proceed. The steward will be notified of any changes made.
</p>

<?php
// Split radio buttons and checkboxes onto multiple lines.
$this->formRadio()->setSeparator('<br />');
$this->formMultiCheckbox()->setSeparator('<br />');
?>

<?= $this->form($detailsForm) ?>

<?php
$groupsJson = json_encode($groups);
$this->inlineScript()
    ->appendScript("var groups = $groupsJson;")
    ->appendFile($this->basePath('js/show-event-field-by-country.js'))
    ->appendFile($this->basePath('js/activate-link-buttons.js'));
