<p>
    Full details of the selected event are displayed here.
    <br />
    Make any changes, choose an approval status and select any additional publishing methods,
    <br />
    then click Submit to proceed. The steward will be notified of any changes made.
</p>

<p><b>
    All dates must be in YYYY-MM-DD format (if typed manually instead of using a
    date picker provided by your browser).
</b></p>

<?php
// Split radio buttons and checkboxes onto multiple lines.
$this->formRadio()->setSeparator('<br />');
$this->formMultiCheckbox()->setSeparator('<br />');
?>

<?= $this->form($detailsForm) ?>
