<?php
declare(strict_types=1);

$editUrl = $this->url('event/edit');
?>
<p>
    This page allows you to review event proposals associated with your group.
    <br />
    Choose a status and press 'Select' to view the different events:
    <br />
    <b>approved</b> events, <b>rejected</b> events and <b>new</b> events (awaiting review).
    <br />
    You can sort by any of the columns by clicking on the column headings.
    <br />
    Click View/Edit for more details and to approve or reject the proposal.
</p>

<?php
// Do not render validation messages alongside each form element.
$this->formRow()->setRenderErrors(false);
echo $this->form($filterForm);
$this->formRow()->setRenderErrors(true);

if (0 < count($events)) {
    ?>

<table id="eventList" class="tablesorter">
    <thead>
        <tr>
            <th>Event Name</th>
            <th>Event Start Date</th>
            <th>Status Last Changed</th>
            <th data-sorter="false">Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($events as $id => $event) { ?>
        <tr>
            <td><?= $this->escapeHtml($event['name']) ?></td>
            <td><?= $this->escapeHtml($event['startdate']) ?></td>
            <td><?= $this->escapeHtml($event['lastchange']) ?></td>
            <td>
                <a href="<?= $editUrl . '?' . http_build_query(['eventid' => $event['eventid']]) ?>">
                    View/Edit
                </a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<p><?= count($events) ?> event(s) displayed.</p>

    <?php
    $this->inlineScript()
        ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js')
        ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.23.3/js/jquery.tablesorter.min.js')
        ->appendFile($this->basePath('js/sort-event-list.js'))
    ?>

    <?php
} else {
    echo "No events found. Try choosing a different status to view.<br />\n";
}
?>
