<p>
    Thankyou for your interest in running an event. To submit your proposal for approval
    by your local group seneschal, please fill in the following form.
    <b>All fields are required unless marked otherwise.</b><br />
    The email address you provide will only be used to contact you regarding this
    submission, including notifications if it is approved, rejected or edited by
    your group seneschal; the email address will not be shared with anyone else.<br />
    If your proposal is approved, the event will automatically appear on the
    Announce mailing list, in the Lochac newsletter 'Pegasus' and on the kingdom calendar.
</p>
<p><b>
    All dates must be in YYYY-MM-DD format (if typed manually instead of using a
    date picker provided by your browser).
</b></p>

<?= $this->form($detailsForm) ?>
