<p>This site is an interface to the database of Lochac group information, with facilities for seneschals to report and update details, and for the public to find group areas and contact information.</p>

<h3 class="center"><a href="<?php echo Zend_Layout::getMvcInstance()->relativeUrl; ?>/index/home">Log in for seneschals' functions</a></h3>
<hr />
<br />

You can either log in above to access pages for group seneschals, or use one of the public facilities in the menu on the left:
<ul>
   <li>Postcode Query: Members of the public can find out which postcodes belong to which group, searching by postcode, range, suburb name or group name.</li>
   <li>Group Roster: View summary information for all groups.</li>
</ul>
