<p>
    The file that you are uploading should be the pc-book_(date).csv file obtained from http://www.auspost.com.au/.
    Make sure you are uploading the correct file before commencing.
    You may need to unzip the file on your machine first.
</p>

<?= $this->form($uploadForm) ?>

<p>This will take several minutes, however it is safe to navigate to another page after the file has uploaded.<br />
Consider checking phpMyAdmin to see the query spike associated with the upload finishing.</p>
