<?php
declare(strict_types=1);
?>
<p>
    From this page, you can edit email aliases associated with your group. 'Alias' gives the
    lochac.sca.org (or other appropriately configured subdomain) address, while 'Destination Address'
    is where mail sent to the alias will be forwarded.
    <br />
    To add a new alias, fill in the last row of the table and press 'Add New'.
    <br />
    To modify an existing alias, change the alias or destination address in the relevant row and press 'Save'.
    <br />
    To remove an alias permanently, press 'Delete' in the relevant row.
    <br />
    Note that the standard email addresses for officers (e.g. "seneschal@group.lochac.sca.org")
    cannot be edited here and must be set through the Regnumator in the Registry application.
</p>

<p>Changes may take up to one hour to take effect.</p>

<?php
// Do not render validation messages alongside each form element.
$this->formRow()->setRenderErrors(false);
echo $this->form($groupSelectForm);

if (isset($permittedDomains)) {
    echo '<p>' . $this->escapeHtml($permittedDomains) . '</p>';
}
?>

<table>
    <tr>
        <th>Alias</th>
        <th>Destination Address</th>
        <th></th>
        <th></th>
    </tr>
    <?php foreach ($aliasForms as $aliasForm) { ?>
    <tr>
        <td colspan='4'>
        <?= $this->form($aliasForm) ?>
        </td>
    </tr>
    <?php } ?>
</table>

<p><?= count($aliasForms) - 1 ?> record(s) displayed.</p>
