<p>
    From this page you can control which subdomains of lochac.sca.org can be used by which groups
    for their email aliases. 'Group' is the name of the group controlling a domain, and 'Domain'
    is the name of the domain which must be lower-case letters and numbers only. For instance, for
    riverhaven.lochac.sca.org the domain is 'riverhaven'. A group can control multiple domains,
    and a domain can be controlled by multiple groups.
    <br />
    To add a new domain, select the desired group and enter an appropriate domain in the last row
    of the table below, and press 'Add New'.
    <br />
    To modify an existing domain, select a new group or change the domain name in the relevant row
    and press 'Save'.
    <br />
    To remove a domain completely, press 'Delete' in the relevant row.
</p>

<p>
    Before changing or removing a domain, ensure the group has no aliases under that domain using
    Manage Group Email Aliases. You may wish to record them so that you can recreate them under
    the new domain.
</p>

<p>Changes may take up to one hour to take effect.</p>

<?php
// Do not render validation messages alongside each form element.
$this->formRow()->setRenderErrors(false);
?>

<style type="text/css">
    table {border: 3px solid #FFFFFF;}
    td {border: 1px solid #FFFFFF;}
</style>
<table>
    <tr>
        <th>Group</th>
        <th>Domain</th>
        <th></th>
        <th></th>
    </tr>
    <?php foreach ($domainForms as $domainForm) { ?>
    <tr>
        <td colspan='4'>
        <?= $this->form($domainForm) ?>
        </td>
    </tr>
    <?php } ?>
</table>
<p><?= count($domainForms) - 1 ?> record(s) displayed.</p>
