<p>
    Select a group from the dropdown menu, then edit the group, seneschal and warrant information
    as necessary. When finished, press 'Submit' at the bottom to save your changes or 'Reset' to
    return to the values saved in the database.
</p>
<p>
    You can also create a new group by selecting 'New Group' from the group select menu and
    submitting appropriate information for that group.
</p>

<?= $this->form($groupSelectForm) ?>
<?= $this->form($detailsForm) ?>
