<style type="text/css">
    body {background-image: none;}
    #Container {width: 100%;}
    .PageContent {max-width: 100%;}
</style>
<table class="colouredTable">
    <tr class="r1">
        <th>Group Name</th>
        <th>Area</th>
        <th>Seneschal</th>
        <th>Email</th>
    </tr>
    <?php
    $i = 0;
    foreach ($this->groupResultSet as $row) { ?>
    <tr class="r<?= ($i & 1) ?>">
        <td>
            <?php if ($row['website'] != '') {
                echo '<a href="', $this->escapeHtmlAttr($row['website']), '">';
                echo $this->escapeHtml($row['groupname']), '</a>';
            } else {
                echo $this->escapeHtml($row['groupname']);
            }

            echo ', ', $this->escapeHtml($row['type']);

            if ($row['status'] != 'live') {
                echo ' (', $this->escapeHtml($row['status']), ')';
            } ?>
        </td>
        <td><?= $this->escapeHtml($row['area']) ?></td>
        <td><?= $this->escapeHtml($row['scaname']), ' (', $this->escapeHtml($row['realname']), ')' ?></td>
        <td><?= $this->escapeHtml($row['email']) ?></td>
    </tr>
        <?php
        $i++;
    } ?>
</table>
