<?php
declare(strict_types=1);

// Do not render validation messages alongside each form element.
$this->formRow()->setRenderErrors(false);
echo $this->form($groupSelectForm);
$this->formRow()->setRenderErrors(true);

$this->inlineScript()->appendFile($this->basePath('js/keepalive-on-change.js'));

if (isset($sampleRoute)) {
    ?>
    <p>Here's a <a href="<?= $this->url($sampleRoute) ?>" target="_blank">sample report</a> (opens in new tab).</p>
    <?php
}
?>

<p>Scroll to the bottom or <a href="#reportTemplate">click here</a> for a template you can copy.</p>

<?php
if (isset($missingWarrant)) {
    ?>
    <p>
        It's not possible to send a report right now because your group and/or your parent group have
        no active seneschal warrant. This needs to be fixed in the Registry (Regnumator).
        <br />
        Contact the Kingdom Seneschal for assistance.
    </p>
    <?php
}

if (isset($detailsForm)) {
    echo $this->form($detailsForm);
}
?>

<hr />

<h2 id="reportTemplate">Report Template</h2>

<p><a href="#top">Back to top</a></p>

<pre data-copyable>
STATISTICS
Members: ??
Active members this quarter (est): ??
Active non-members this quarter (est): ??
Total funds in bank (from your latest Reeve report): $???

"Drop-dead" Deputy name, email and telephone

Summary of Regular Activities

Special Achievements and Ideas That Worked

Summary of Events

Problems of Note (please include names, not just "somebody went and...") [in confidence]

Questions [in confidence]

Plans for the future, ideas etc.

General Comments

Officers - brief *summary* of key points (please don't paste the whole report!)

Marshal

Herald

Arts and Sciences

Reeve

Constable

Chirugeon

Chronicler and/or Webminister

Chatelaine/Hospitaller

Other offices (e.g. Lists, Historian, Youth, DEI etc)

Subgroups (including Hamlets)
</pre>
