<?php
declare(strict_types=1);
?>
<div data-copyable>
College of St Genevieve<br />
<br />
Date: 15/02/21<br />
Members: 5<br />
Active members this quarter: 5<br />
Active non-members this quarter: 13<br />
Total funds in bank: $450, including $150 uni grant<br />
<br />
REGULAR ACTIVITIES<br />
=================<br />
A&S every week, about 4-6 people most nights<br />
<br />
ACHIEVEMENTS<br />
============<br />
New College banner and replaced old serving dishes.<br />
<br />
EVENTS<br />
======<br />
Big push at Orientation with lots of people saying they would come to the
Collegium but fewer turned up than expected.<br />
<br />
PROBLEMS [in confidence]<br />
========================<br />
Getting people along to early activities!<br />
<br />
QUESTIONS [in confidence]<br />
=========================<br />
What happens if we can't get a new Seneschal when I leave town in December?<br />
<br />
PLANS<br />
=====<br />
Maybe ask the Barony to subsidise a small feast to encourage new people.<br />
<br />
GENERAL COMMENTS<br />
=================<br />
<br />
SUMMARY OF OFFICERS<br />
====================<br />
<br />
== Herald<br />
No court heraldry<br />
One consultation and submission.<br />
<br />
== Arts and Sciences<br />
Weekly A&S well attended, a gift project underway for Crown.<br />
Collegium did OK for the day but the feast made a loss - too much food and
not enough people.<br />
<br />
== Reeve<br />
Bank balance healthy. Need to sort out more signatures.
</div>
