<?php
declare(strict_types=1);
?>
<div data-copyable>
Report from the Canton of Overyonder<br />
<br />
Date: 28/02/21<br />
Submitted by: Lord Erami<br />
(My apologies for the lateness due to a medical issue.)<br />
<br />
STATISTICS<br />
==========<br />
Members: 32<br />
Active members this quarter: 20<br />
Active non-members this quarter: about 6<br />
Total funds in bank: $1,423<br />
<br />
REGULAR ACTIVITIES<br />
=================<br />
Rapier and Archery are all regularly attended. Usually at least 4-6+ on the archery
line and similar training rapier. Need to look at getting more heavy training support.<br />
<br />
Group meeting with A&S held monthly; hall costs are going up so we need to ask
for some short-term Baronial funds as donations will no longer cover it.<br />
<br />
ACHIEVEMENTS<br />
==========<br />
Archery is popular and brings in new people. Some members from here attended the
Medieval Carnival and came back with ideas for demos we could run here. Need to
build on that.<br />
<br />
EVENTS<br />
============<br />
IKAC day - 31 people including a small group of new people<br />
<br />
PROBLEMS<br />
=========<br />
Need to upgrade the lender archery equipment.<br />
<br />
I need to hand on the Seneschal position due to health issues. Our local knight
Sir Talksalot is keen but I wouldn't recommend him if he applies as he tends to
be dominating and doesn't do what he says he will. I will start the advertising
process next week (have a couple of possibilities lined up).<br />
<br />
One of our members needed to be spoken to about their behaviour at an event,
this was dealt with within the group and sorted.<br />
<br />
Hospitaller has not been seen so will be replacing her shortly. (At one event
with newcomers she was there but didn't do anything).<br />
<br />
QUESTIONS<br />
=========<br />
<br />
PLANS<br />
=====<br />
Still working on local martial arts groups to see if we can build up heavy
fighting. Currently have three authorised fighters.<br />
<br />
GENERAL COMMENTS<br />
=================<br />
Our officers are improving reporting to me and uplines but it remains ad hoc
and late. I have asked them to set reminders for reports and to be more
organised. I haven't been able to get to events and meetings lately so I have
mentioned that I'd like to see a little more detail, especially regarding new
problems and future plans. But it's good to see less grumbling about the
relationship with the Barony.<br />
<br />
SUMMARY OF OFFICERS<br />
====================<br />
<br />
== Marshal<br />
I have been authorized for rapier. Practice has been well attended, with
particular thanks going to Lady Strongeye for driving the archery practice
that has been popular.<br />
<br />
== Herald<br />
We plan to do some banner gifts for the Crown event. Four name and/or device
submissions have been submitted to Rocket, with another two in the works.<br />
<br />
== Arts and Sciences<br />
No officer at present. We continue to support each other in arts during our
monthly gatherings.<br />
<br />
== Reeve<br />
The new reeve, Lord Cashin was the first officer to submit report this time!
He looks like he will work well with the baronial oversight (this has been
an issue in the past).<br />
$1243 in our account.<br />
<br />
== Constable<br />
No officer at present, Baronial Constable supporting in this role.<br />
<br />
== Chirurgeon<br />
No Officer at present<br />
<br />
== Chronicler/Webminister<br />
None at present, announcements going through the mailing list and official
Facebook page, I moderate them if needed (nothing needed this quarter).<br />
<br />
== Chatelaine/Hospitaller<br />
Everyone!<br />
<br />
== Lists<br />
We have list-keepers at events, nobody holds the office at present.
</div>
