<?php
declare(strict_types=1);
?>
<div data-copyable>
Report from the Shire of Camelot<br />
<br />
Date: 21 September 650AD<br />
Submitted by: Arthur of the Britons (Peter O'Toole)<br />
<br />
STATISTICS<br />
==========<br />
Members: 15<br />
Active members this quarter: 7<br />
Active non-members this quarter: 3<br />
Total funds in bank: $1013.05<br />
<br />
REGULAR ACTIVITIES<br />
=================<br />
Monthly Council, most attending virtually.<br />
Heavy practice continues weekly at Lord Mordred's house.<br />
<br />
ACHIEVEMENTS<br />
============<br />
Had a Grail Quest, only four people died and most returned. Eventually.<br />
<br />
EVENTS<br />
======<br />
Grail Quest - Feb 10, Cornwall Park, 16 people there.<br />
<br />
PROBLEMS<br />
=========<br />
Hard to get people to organise events. Heavy training is a bit hard to break
into as it occurs at a private location which puts some off - there is talk
about starting another training group in a park somewhere.<br />
<br />
The Green Knight Feast Steward has misplaced their receipts so hasn't accounted
for the $200 advanced from the Shire (net takings were banked ok). This is
being followed up.<br />
<br />
QUESTIONS<br />
=========<br />
Can we make an approximate list of the Feast costs to finalise Feast accounts?
What validation/sign-off is needed to accept that?<br />
<br />
PLANS<br />
=====<br />
Attempting to get a regular Seamsters happening and working on getting a couple
of fighters marshalled to help run an alternative fighter practice.<br />
<br />
We'd like to invite the next Crown here for an event as it will have been nearly
4 years since the last visit and by we definitely have some people needing awards!
A Crown presence in planning should encourage more activity.<br />
<br />
GENERAL COMMENTS<br />
=================<br />
Finding it hard to motivate people. People want things to happen but aren't
overly inclined to initiate things themselves. Hard with only 6 or 7 members
who are actively doing things.<br />
<br />
SUMMARY OF OFFICERS<br />
====================<br />
<br />
== Marshal<br />
Training happening so that we have additional marshals and can extend fighter
practice. Big thanks to Galahad for spear-heading that. Maybe see if we can
get old armour out of non-active members.<br />
<br />
== Herald<br />
Working on three submissions to go to the college of Heralds.<br />
<br />
== Arts and Sciences<br />
Lady Guinivere sponsored an A&S Challenge which is being run online to encourage
participation. It will run to Shire Anniversary and has had two entries already.<br />
<br />
== Reeve<br />
When I took over the Reeve position had not been officially filled since October
649. No extra financial information was handed over from the previous but the
Dropbox had enough to work with.<br />
<br />
Funds from the Green Knight Feast have not yet been finalised as there is an
issue with receipts, but the event did make a profit.<br />
<br />
== Constable<br />
currently vacant.<br />
<br />
== Chirurgeon<br />
Merlin has taken this on; no incidents.<br />
<br />
== Chronicler/Webminister<br />
The webpage has been completely updated by me (Seneschal).<br />
<br />
== Chatelaine/Hospitaller<br />
currently vacant<br />
<br />
== Lists<br />
currently vacant, Lady Ofshallot is no longer with us<br />
<br />
SUMMARY OF SUB-GROUPS<br />
======================<br />
<br />
Summary report for College of St Genevieve<br />
<br />
The college had an A&S event in Sept which had a small loss due to a few
people who had booked not prepaying or turning up, and the feasting steward
not being completely familiar with quantity cooking.
</div>
