<?php
declare(strict_types=1);
?>
<div data-copyable>
Barony of Wearzat<br />
<br />
Date: 22/02/21<br />
Submitted by: Grue de Weed (Jo Smith)<br />
<br />
STATISTICS<br />
==========<br />
Members: 112<br />
Active members this quarter: 70ish<br />
Active non-members this quarter: 40ish<br />
Total funds in bank: $24800 (less $11000 due to pay site fees for Winter Camp)<br />
Members include 25 minors; around 40 non-members also attend big events.<br />
The Canton of Overyonder has 32 members, is recruiting strongly from local
martial arts groups but reporting is patchy.<br />
The College of St Chrissy has 12 members though only two seem active.<br />
<br />
REGULAR ACTIVITIES<br />
=================<br />
Barony:<br />
Monthly Council Meeting, Tourney<br />
Weekly: heavy and archery practices, rapier is very patchy last quarter<br />
Fortnightly: dance, brewers - the latter got a big membership/activity bump
after the stall at Brewfest<br />
<br />
Canton:<br />
Monthly Gathering: for Canton officer, A&S, rapier<br />
<br />
College:<br />
O week + weekly for first month, nothing since then<br />
<br />
ACHIEVEMENTS<br />
============<br />
Five new active people (two already members) due to BrewFest.<br />
<br />
Got more people joining the email list after strong drive re communication.
Strong reinforcement re list behaviour has helped with some problems though
Sir Talksalot has continued to demonstrate some concerning behaviour (have
asked Sir NicenCheerful to have a word).<br />
<br />
We put in a bid for the All Hallows Crown event; some fire-fighting was needed
to help the event steward and Baronial Council understand their respective roles
and responsibilities. Trying to encourage constructive help and reduce
unnecessary criticism or patch-defending.<br />
<br />
EVENTS<br />
======<br />
Aug: Crown bid workshop - good involvement from Overyonder, helpful planning
meeting and some projects to be taken further<br />
<br />
Aug 20: stall at Brewfest - we had only two people there and recruited five!<br />
<br />
Sep 11: Demo at Medieval Carnival - heavy fighting, weaving and singing; handed
out flyers and cards; publicised the next Tourney to encourage follow-up; strong
interest from other groups re heavy and rapier; invited to demo at karate dojo in Nov<br />
<br />
5/9 - IKAC Archery Shoot - Overyonder held this, good attendance.<br />
<br />
PROBLEMS [in confidence]<br />
========================<br />
Getting new stewards continues to be difficult partly because long-established
members are holding onto events or being overly critical of new people and new
ideas. Council discussed the problem and we will look at strategies including
training for new stewards and talking to those involved.<br />
<br />
No other major problems of note. We have enthusiasm with the Crown bid and hope
to grow on that, so our major challenge is to capitalise on this momentum. Do
need to look at the College and how it can be revived - O week is early next
year so will try to get them to plan early, ‘cos students are typically hard
to reach over Christmas/NY.<br />
<br />
QUESTIONS [in confidence]<br />
=========================<br />
The university will let us have two non-student officers in a campus club - is
it OK for the Barony to provide Seneschal and Reeve?<br />
<br />
Can we decline a booking from a member who has yet to pay for a previous event?
(see Reeve's report)<br />
<br />
PLANS<br />
=====<br />
I am planning a visit to the Canton and hold an Officers' meeting while there
to encourage them to collaborate and bring up issues before they become
regional problems.<br />
<br />
GENERAL COMMENTS<br />
=================<br />
Currently in the process of organising a lease for our hall. It has been
signed off by SCA Ltd, and just waiting for final sign-off by the council.<br />
<br />
SUMMARIES OF OFFICERS REPORTS<br />
====================<br />
<br />
== Marshal - Sir Talksalot<br />
Despite extensive prompting, no report. I have indicated at Baronial Council
that everyone must report, but nothing. The deputies, Lady Helpful (Archery)
and Lord Cheerful (Rapier) report regularly and comprehensively.<br />
<br />
There are no known outstanding Marshal issues aside from the lack of a report.<br />
<br />
== Herald - Lady Escutcheon<br />
The Herald has submitted a quarterly report, reproduced below. There are no
outstanding issues, though submissions continue to be slow. He has plans for
an applied heraldry A&S workshop which is attracting keen interest.<br />
<br />
== Arts and Sciences Officer - Baron Triesalot<br />
The A&S officer has submitted a comprehensive report - can forward if asked.
A&S continues to grow strongly within the Barony and Triesalot is doing an
excellent job encouraging this growth especially in new areas. The Canton's
A&S nights have proven very popular for their informal nature and the
willingness of members to assist newcomers (particularly good to hear given
earlier difficulties with cliqueness on the part of the House of Ussher members).<br />
<br />
== Reeve - Lady Casshin<br />
The Reeve continues to do an exemplary job and has sorted out signaturies
without incident. Her full report is appended. All good though he did comment
that Talksalot still hasn't paid his WinterCamp fees; is suggesting we
decline future bookings from him until this is done.<br />
<br />
== Constable - Robert Peel<br />
Has done a great job since the recent officer changeover. He has streamlined
sign-in for practices. The new Winter Camp Night Watch has prevented problems
we had last year at this site (two public incursions). The Canton constable
has reported good events, no incidents and no one has died<br />
<br />
We have no Chirurgeon but has people we can call on for bigger events. We had
one at the Carnival on standby,not needed.<br />
<br />
== Chronicler/Webminister - Lady Worde Smith<br />
Recently took over and has left the newsletter much the same while
concentrating on the website. Has raised concerns about some social media
postings and wants to clarify which are our official Facebook pages. I
pointed her at the Kingdom Social Media officer.<br />
<br />
== Chatelaine/Hospitaller - Mistress Friend<br />
Waiting on officer change-over (currently out for public consultation) but
continues to work hard to bring in new people. Report is attached, main
point being new buddy system plan to help acculturate newcomers; also
plans for improving Hire Garb offerings.<br />
<br />
== Keeper of the Lists - Lord Gilbert Sullivan<br />
Attended lists for Baronial Tourney and Carnival demonstration. The Canton
had no event that required a listkeeper. All good.<br />
<br />
SUMMARY OF SUB-GROUPS<br />
======================<br />
<br />
Summary report for Canton of Overyonder: Seneschal Lord Ereami<br />
<br />
No report but Ereami has been in hospital for minor surgery and should get
it to me within the week. I will be following up so he submits through the
Quarterly Report system this time. In general things seem to be progressing
well over there.<br />
<br />
The new Canton Reeve reported to his Baronial counterpart and has brought
their financial information up to date, which is great progress. I hope
marks a new stage of clear communication in that area.
</div>
