<?php
// Set up main menu based on authLevel. All cases fall through to build an authLevel-cumulative menu.
// Links are relative to application root.
if (!isset($authLevel)) {
    $authLevel = 'anyone';
}

$menu = [];
switch ($authLevel) {
    case 'admin':
        $menu[] = [
            'link' => ['controller' => 'group', 'action' => 'edit'],
            'name' => 'Edit Group Details'
        ];
        $menu[] = [
            'link' => ['controller' => 'group', 'action' => 'close'],
            'name' => 'Close a Group'
        ];
        $menu[] = [
            'link' => ['controller' => 'postcode', 'action' => 'assign'],
            'name' => 'Assign Postcodes'
        ];
        $menu[] = [
            'link' => ['controller' => 'postcode', 'action' => 'upload'],
            'name' => 'Upload Postcodes File'
        ];
        $menu[] = [
            'link' => ['controller' => 'group', 'action' => 'domains'],
            'name' => 'Manage Group Email Domains'
        ];
        // Fall through
    case 'user':
        $menu[] = [
            'link' => ['controller' => 'group', 'action' => 'aliases'],
            'name' => 'Manage Group Email Aliases'
        ];
        $menu[] = [
            'link' => ['controller' => 'report', 'action' => null],
            'name' => 'Quarterly Reports'
        ];
        $menu[] = [
            'link' => ['controller' => 'event', 'action' => 'list'],
            'name' => 'Event List'
        ];
        $menu[] = [
            'link' => ['controller' => 'group', 'action' => 'baron-baroness'],
            'name' => 'Baron and Baroness Details'
        ];
        // Fall through
    default: // Equivalent to case 'anyone'
        $menu[] = [
            'link' => ['controller' => 'postcode', 'action' => null],
            'name' => 'Postcode Query'
        ];
        $menu[] = [
            'link' => ['controller' => 'group', 'action' => null],
            'name' => 'Group Roster'
        ];
        $menu[] = [
            'link' => ['controller' => 'event', 'action' => null],
            'name' => 'Submit Event Proposal'
        ];
        break;
}
?>

<?= $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Lochac Seneschals\' Database')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink()
            ->prependStylesheet($this->basePath('css/seneschal.css'))
            ->prependStylesheet($this->basePath('css/sen-print.css'), $media = 'print')
        ?>

        <?= $this->headScript() ?>
    </head>
    <body <?= isset($fullWidth) && $fullWidth ? 'class="fullwidth"' : '' ?>>
        <div id="Container">
        <div class="Navigation">
            <img src="<?= $this->basePath('img/kingdom-seneschal-device.png') ?>"
                alt="Office of the Seneschal of Lochac" width="250" height="269" usemap="#SenLinks" />
            <map id="SenLinks" name="SenLinks">
                <area shape="poly" coords="83,47,165,48,165,104,125,144,83,103"
                    href="https://lochac.sca.org/lochac" target="_blank" alt="Kingdom of Lochac" />
                <area shape="circle" coords="125,197,33" href="https://seneschal.lochac.sca.org"
                    alt="The Office of the Seneschal" />
            </map>

            <p>
                <a href="https://lochac.sca.org/lochac">Lochac Homepage</a><br />
                <a href="https://seneschal.lochac.sca.org">From the Seneschal <small>(Home)</small></a><br />
                <a href="<?= $this->url('default') ?>">Database</a><br />
                <span class="subNav">
    <?php foreach ($menu as $item) { ?>
                    <a href="<?= $this->url('default', $item['link']) ?>"><?= $item['name'] ?></a><br />
    <?php } ?>
                </span>
                <?php
                if ($authLevel != 'anyone') { ?>
                <hr />
                <a href="<?= $this->url('default', ['controller' => 'auth', 'action' => 'logout']) ?>">Log Out</a>
                <?php } ?>
            </p>

            <img alt="Navigation Border" src="<?= $this->basePath('img/nav-bottom.png') ?>" width="250" height="59"/>
        </div>

        <div class="PageContent">
            <div class="headerImg">
                <img alt="The Office of the Seneschal - Kingdom of Lochac"
                    src="<?= $this->basePath('img/office-of-the-seneschal.png') ?>" width="555" height="81"/>
            </div>
            <a name="top"></a>

            <h1 class="center"><?= $this->escapeHtml($this->title) ?></h1>

    <?php
    if (isset($this->alerts)) {
        foreach ($this->alerts as $alert) {
            if (is_array($alert)) { ?>
            <div class="<?= $alert['type'] ?>"><?= $alert['message'] ?></div><br />
            <?php   } else { ?>
                <?= $alert ?><br />
            <?php   }
        }
    } ?>

            <!-- Start page content -->
    <?= $this->content ?>

            <!-- End page content -->

            <div class="copyright">
                <hr />
                <p>
                    This page is maintained by the Publications/Technical Deputy to the Kingdom Seneschal
                    <br />
                    Comments or suggestions to
                    <a href="mailto:information&#64;lochac.sca.org">information&#64;lochac.sca.org</a>
                </p>
                <small>
                    Application Code: Lord Edmund Kerr
                    <br />
                    Site Design: Lord Ronan mac Briain
                </small>
            </div>
        </div>
    </div>

        <?= $this->inlineScript()
            ->appendFile($this->basePath('js/focus-on-first-error.js'))
            ->appendFile($this->basePath('js/google-analytics.js'))
        ?>
    </body>
</html>
