<?php $url = Zend_Layout::getMvcInstance()->relativeUrl;
$thisUrl = $_SERVER['REQUEST_URI']; ?>
<p>This page allows you to review event proposals associated with your group.<br />
Choose a status and press 'Select' to view the different events:<br />
<b>approved</b> events, <b>rejected</b> events and <b>new</b> events (awaiting review).<br />
You can sort by any of the columns by clicking on the column headings.<br />
Click View/Edit for more details and to approve or reject the proposal.</p>

<?php
echo $this->groupSelectForm;
if(0 < count($this->events)) {
?>


<style type="text/css">
    table {border: 3px solid #FFFFFF;}
    td, th {border: 1px solid #FFFFFF;}
</style>
<table>
    <tr>
        <th><a href='<?php echo $thisUrl; ?>&sort=name'>Event Name</a></th>
        <th><a href='<?php echo $thisUrl; ?>&sort=startdate'>Event Start Date</a></th>
        <th><a href='<?php echo $thisUrl; ?>&sort=lastchange'>Status Last Changed</a></th>
        <th>Actions</th>
    </tr>
<?php foreach($this->events as $id => $event) { ?>
    <tr>
        <td><?php echo $this->escape($event->name); ?></td>
        <td><?php echo $this->escape($event->startdate); ?></td>
        <td><?php echo $this->escape($event->lastchange); ?></td>
        <td><a href='<?php echo $url; ?>/event/edit?eventid=<?php echo $event->eventid; ?>'>View/Edit</a></td>
    </tr>
<?php } ?>
</table>
<?php
echo count($this->events) . " event(s) displayed.<br />\n";
} else {
    echo "No events found. Try choosing a different status to view.<br />\n";
}
?>
